#:kivy 2.0.0

<SettButton@Button>:
    size_hint: None, None
    height: max(50, self.texture_size[1] + dp(20))
    font_size: '20dp'
    bold: True
    italic: True
    background_color: [float(25)/255,float(63)/255,float(90)/255,0.4]
    color:[float(233)/255, float(147)/255, float(34)/255,0.7] 
    # [float(233)/255, float(147)/255, float(34)/255,1] [float(25)/255,float(63)/255,float(90)/255,0.7]
